**NUMPY**

Aula 10

In [1]:
import numpy as np

In [3]:
grades = np.array([7.5, 8.0, 6.5, 9.0])
print(grades)

[7.5345677 8.        6.5       9.       ]


**Lista e Array**

In [19]:
list = [10, 20, 30]
array = np.array([list])

print(list + [5]) # append the number 5 to the list
print(array + 5) # sum 5 to each item of the list - "vetorização"

[10, 20, 30, 5]
[[15 25 35]]


**Vetorização**

In [22]:
prices = [100, 200, 300]
discounted_prices = []

for price in prices:
    discounted_prices.append(price * 0.9)

print(discounted_prices)

[90.0, 180.0, 270.0]


In [21]:
prices = np.array([100, 200, 300]) # It´s a python's list -> array
discounted_prices = prices * 0.9

print(discounted_prices)

[ 90. 180. 270.]


**Array com números sequenciais**

In [14]:
numbers = np.arange(0, 10)
print(numbers)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
even = np.arange(0, 11, 2)
print(even)

[ 0  2  4  6  8 10]


In [17]:
odd = np.arange(1, 11, 2)
print(odd)

[1 3 5 7 9]


In [24]:
zeros = np.zeros(10) # Create an array of zeros and ones
ones = np.ones(10)

print(zeros)
print(ones)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [25]:
values = np.ones((10, 5)) # Create a matrix with 10 rows and 5 columns
print(values)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Valor Mínimo e Máximo**

In [28]:
values = np.linspace(0, 10, 5) # Create 5 evenly spaced values between 0 and 10
print(values)

[ 0.   2.5  5.   7.5 10. ]


In [36]:
grades = np.array([
    [8.0, 10, 8.5],
    [9.2, 7.5, 4.5],
    [10, 8.9, 5.5],
    [4.5, 8.6, 9]
])

print(grades.ndim) # dimension
print(grades.shape) # number of rows and columns
print(grades.size) # total number of elements
print(grades.dtype)

2
(4, 3)
12
float64


In [43]:
grades = np.array([
    [8.0, 10, 8.5],
    [9.2, 7.5, 4.5],
    [10, 8.9, 5.5],
    [4.5, 8.6, 9]
])

print(grades[0, 0])
print(grades[0])
print(grades[0, 0], grades[3, 2])
print(grades[-1, -1])
print(grades[:, 0]) # Column


8.0
[ 8.  10.   8.5]
8.0 9.0
9.0
[ 8.   9.2 10.   4.5]


In [47]:
grades = np.array([8.0, 10, 8.5])

print(grades + 1)
print(grades - 1)
print(grades * 1)
print(grades / 2)



[ 9.  11.   9.5]
[7.  9.  7.5]
[ 8.  10.   8.5]
[4.   5.   4.25]


**Operações entre Arrays**

In [48]:
grades_av1 = np.array([8.0, 10, 8.5, 10])
grades_av2 = np.array([4.5, 8, 7.5, 9])

average_grades = ((grades_av1 + grades_av2) / 2)
print(average_grades)

[6.25 9.   8.   9.5 ]


In [55]:
grades_av1 = np.array([8.0, 10, 8.5, 10])

print(grades_av1.sum())
print(grades_av1.mean())
print(grades_av1.min())
print(grades_av1.max())
print(grades_av1.std())

36.5
9.125
8.0
10.0
0.8926785535678563


In [49]:
grades_first_semester = np.array([8.0, 10, 8.5, 10])
grades_second_semester = np.array([4.5, 8, 7.5, 9])

average = np.mean((grades_first_semester + grades_second_semester) / 2)

print(average)  # Overall average grade

8.1875


**Média por coluna**

In [56]:
grades = np.array([
    [8.0, 10, 8.5],
    [9.2, 7.5, 4.5],
    [10, 8.9, 5.5],
    [4.5, 8.6, 9]
])

print(grades.mean(axis=0))

[7.925 8.75  6.875]


In [61]:
grades = np.array([8.0, 10, 8.5, 10])

print(grades > 8)
print(grades[grades > 8])
print((grades > 8).sum())

[False  True  True  True]
[10.   8.5 10. ]
3


In [64]:
grades= np.array([8.0, 10, 8.5, 10, 5.5])


average = grades.mean()
aprovados = average >= 7
print(grades[aprovados])
print(grades[aprovados])

[]
[]
